### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by sarala777** [VityaVitalich/MLEM#1]
Hi Could yo share any of the 5 data that is listed for running the code.
Thanks in advance.

**Comment by VityaVitalich** [comment]
Hello!

Thank you for noticing, it was a problem with provided links in README. We have fixed it, now all the data is availible.

Please do not hesitate to contact us if any problems with our code occurs

**Comment by sarala777** [comment]
> Hi Could yo share any of the 5 data that is listed for running the code. Thanks in advance.

Thanks, the link works now.
I will get back in case of queries.
Have a nice day!

**Comment by sarala777** [comment]
Thanks, the link works now.
I will get back in case of queries.
Have a nice day!
